import type { GetStaticProps, NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Quiz from "../components/Quiz/quiz";
import styles from "../styles/Home.module.css";
import prisma from "../lib/prisma";
import TopMenu from "../components/Menu/TopMenu";

export const getStaticProps: GetStaticProps = async () => {
  console.log("Try to retrieve user");
  let user = await prisma.user.findFirst();
  user = JSON.parse(JSON.stringify(user));
  return {
    props: { user },
    revalidate: 10,
  };
};
const Home: NextPage = ({}) => {
  return (
    <div className={styles.container}>
      <Head>
        <title >Spot The Bug</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main id="main" className={styles.main}>
        <TopMenu />
        <h1 className={styles.title}>Spot The Bug</h1>
        <h3>Javascript - Simple questions, surprising answers</h3>
        <Quiz />
      </main>

      <footer className={styles.footer}>
        <a
          href="https://philopoellmann.com"
          target="_blank"
          rel="noopener noreferrer"
        >
          © Philo Pöllmann
        </a>
      </footer>
    </div>
  );
};

export default Home;
